#!/usr/bin/env bash

set -eo pipefail

PROGNAME="kubectl iexec"
KUBECTL_IEXEC_DEFAULT_COMMAND=${KUBECTL_IEXEC_DEFAULT_COMMAND:=/bin/sh}
KUBECTL_IEXEC_NS_COLOR=${KUBECTL_IEXEC_NS_COLOR:="\033[36m"}

_KUBECTL_IEXEC_VERSION="0.1.0"

show_usage() {
  cat <<_EOS_ 1>&2
Usage: $PROGNAME [OPTIONS...] <query> -- <command>
OPTIONS:
  -h, --help               Show help for '$PROGNAME'
  -n, --namespace string   The name of namespace to use
  --context string         The name of kubeconfig context to use
Examples: 
  $PROGNAME -n kube-system kube-proxy -- /bin/sh
  $PROGNAME istiod --context my-cluster
_EOS_
}

prompt_help () {
  printf "See '$PROGNAME --help' for usage.\n"
}

buildkcmd() {
  cmd="kubectl get pod"
  if [[ -v OPT_NS ]]; then cmd+=" -n $OPT_NS"; else cmd+=" -A"; fi
  if [[ -v OPT_CTX ]]; then cmd+=" --context $OPT_CTX"; fi
  cmd+=" --field-selector status.phase=Running -o jsonpath=\"{range .items[*]}{'${KUBECTL_IEXEC_NS_COLOR}['}{.metadata.namespace}{']\033[0m '}{.metadata.name}{' '}{.spec.containers[*].name}{'\n'}{end}\""
  echo "$cmd"
}

iexec() {
  kcmd=$(buildkcmd)

  fzf_options="--ansi --exit-0 --nth 2 --with-nth 1,2 --height 40%"
  if [[ -v OPT_QUERY ]]; then fzf_options+=" --query $OPT_QUERY"; fi

  read ns pod containers < <(eval $kcmd | fzf $fzf_options | tr -d '[]')
  container=$(echo ${containers} | tr ' ' '\n' | fzf --exit-0 --select-1)

  cmd=${OPT_CMD-${KUBECTL_IEXEC_DEFAULT_COMMAND}}
  ctx=${OPT_CTX-$(kubectl config current-context)}

  kubectl exec -it $pod -c $container -n $ns --context $ctx -- $cmd
}

while (( $# > 0 )); do
  case "$1" in
    -h | --help)
      show_usage
      exit 1
      ;;
    --version)
      echo ${_KUBECTL_IEXEC_VERSION}
      exit 1
      ;;
    -n | --namespace* )
      if [[ "$1" =~ = ]]; then OPT_NS="${1#*=}"; else OPT_NS="$2" && shift; fi
      ;;
    --context* )
      if [[ "$1" =~ = ]]; then OPT_CTX="${1#*=}"; else OPT_CTX="$2" && shift; fi
      ;;
    -- )
      shift
      OPT_CMD="$@"
      break
      ;;
    -* | --* )
      printf "Error: unknown flag: $1\n"
      prompt_help
      exit 1
      ;;
    * )
      OPT_QUERY="$1"
      ;;
  esac
  shift
done

iexec
